//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ex_id { get; set; }
        public Nullable<System.DateTime> ex_date { get; set; }
        public Nullable<int> ex_fk_stu { get; set; }
        public string ex_name { get; set; }
        public Nullable<int> ex_score { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
