//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Question
    {
        public int qu_id { get; set; }
        [Display(Name = "Question")]
        public string qu_text { get; set; }
		[Display(Name = "Option A")]

		public string opA { get; set; }
		[Display(Name = "Option B")]

		public string opB { get; set; }
		[Display(Name = "Option C")]

		public string opC { get; set; }
		[Display(Name = "Option D")]

		public string opD { get; set; }
		[Display(Name = "Correct Answer")]

		public string Cop { get; set; }
        public Nullable<int> q_fk_catid { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
