//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Student
	{
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Exams = new HashSet<Exam>();
        }
    
        public int st_id { get; set; }
		[Display(Name = "Name")]
		[Required(ErrorMessage = "Name is required")]
		public string st_name { get; set; }
		[Display(Name = "Password")]
		[Required(ErrorMessage = "Password is required")]
		public string st_password { get; set; }
		[Display(Name = "Image")]
		[Required(ErrorMessage = "Image is required")]
		public string st_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam> Exams { get; set; }
    }
}
